[Draw]
# Indicates that the image will be drawn in one block.
render_all_at_once=true
# If `render_all_at_once` is false then in one draw will be used that many blocks.
blocks_per_draw=200

[Image]
# Size of output image.
image_width=720
image_height=720
# Name of the output file.
file_name=file
# The path to save the output file. This can be relative to the exe file or absolute.
output_path=.

[Quality]
# Number of AntyAliasing Iterations. Optimized.
aa_iter=1
# Number of iterations used when calculating refraction i reflection. Optimized.
ref_iter=4
# Number of Global Illumination iterations. For Performance 2, for quality 4.
gl_iter=1
# Number of indirect rays casted from diffuse hit point.  I think its good enough.
ind_rays=75
# Number of shadow samples. Optimized.
shadow_samples=50
